coverage:
  status:
    project:
      logsCode:
        target: auto
        flags:
          - logsCode
      serviceCode:
        target: auto
        flags:
          - serviceCode
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true
  branches: ["main"]
flags:
  core:
    paths:
      - packages/core/
    carryforward: true
  sdk:
    paths:
      - packages/drupal-js-sdk/
    carryforward: true
