packages:
  - apps/*
  - packages/*
  - '!**/test/**'

overrides:
  '@babel/helpers@<7.26.10': '>=7.26.10'
  '@babel/runtime@<7.26.10': '>=7.26.10'
  '@babel/traverse@<7.23.2': '>=7.23.2'
  axios@<0.30.0: '>=0.30.0'
  axios@>=0.8.1 <0.28.0: '>=0.28.0'
  axios@>=1.0.0 <1.6.0: '>=1.6.0'
  axios@>=1.0.0 <1.8.2: '>=1.8.2'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  braces@<3.0.3: '>=3.0.3'
  cross-spawn@<6.0.6: '>=6.0.6'
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  esbuild@<=0.24.2: '>=0.25.0'
  follow-redirects@<1.15.4: '>=1.15.4'
  follow-redirects@<=1.15.5: '>=1.15.6'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  micromatch@<4.0.8: '>=4.0.8'
  nanoid@<3.3.8: '>=3.3.8'
  postcss@<8.4.31: '>=8.4.31'
  prismjs@<1.30.0: '>=1.30.0'
  rollup@>=3.0.0 <3.29.5: '>=3.29.5'
  semver@<5.7.2: '>=5.7.2'
  semver@>=6.0.0 <6.3.1: '>=6.3.1'
  semver@>=7.0.0 <7.5.2: '>=7.5.2'
  tmp@<=0.2.3: '>=0.2.4'
  tough-cookie@<4.1.3: '>=4.1.3'
  vite@<4.5.10: '>=4.5.10'
  vite@<4.5.11: '>=4.5.11'
  vite@<4.5.12: '>=4.5.12'
  vite@<4.5.13: '>=4.5.13'
  vite@<=4.5.13: '>=4.5.14'
  vite@<=4.5.5: '>=4.5.6'
  vite@>=4.0.0 <4.0.5: '>=4.0.5'
  vite@>=4.0.0 <4.5.4: '>=4.5.4'
  vite@>=4.0.0 <=4.5.1: '>=4.5.2'
  vite@>=4.0.0 <=4.5.2: '>=4.5.3'
  vite@>=4.0.0 <=4.5.3: '>=4.5.4'
  word-wrap@<1.2.4: '>=1.2.4'
  ws@>=8.0.0 <8.17.1: '>=8.17.1'
  yaml@>=2.0.0-5 <2.2.2: '>=2.2.2'
