site_name: Drupal JavaScript SDK
repo_url: https://github.com/d34dman/drupal-js-sdk
repo_name: "@d34dman/drupal-js-sdk"
site_author: Shibin Das (D34dMan)
theme:
  name: material
  
copyright: Copyright 2025 Shibin Das (D34dMan)

markdown_extensions:
  - admonition
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences