name: Codecov @drupal-js-sdk/core
on:
  push:
    branches:
      - main
    paths:
      - 'packages/core/src/**'
      - 'packages/core/package.json'
      - '.github/**'

defaults:
 run:
   working-directory: 'packages/core'

jobs:
  codecov:
    name: Execute test suite for @drupal-js-sdk/core
    runs-on: ubuntu-latest
    env:
      node-version: 16.x
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      working-directory: './'
      run: |
        yarn install
        yarn build
    - name: Run test suite
      run: yarn test
    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        name: '@drupal-js-sdk/core'
        flags: '@drupal-js-sdk/core'
        
