name: Codecov drupal-js-sdk
on:
  push:
    branches:
      - main
    paths:
      - 'packages/drupal-js-sdk/src/**'
      - 'packages/drupal-js-sdk/package.json'
      - '.github/**'

defaults:
 run:
   working-directory: 'packages/drupal-js-sdk'

jobs:
  codecov:
    name: Execute test suite for drupal-js-sdk
    runs-on: ubuntu-latest
    env:
      node-version: 16.x
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      working-directory: './'
      run: |
        yarn install
        yarn build
    - name: Run test suite
      run: yarn test
    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        name: 'drupal-js-sdk'
        flags: 'drupal-js-sdk'
