name: Codecov
on:
  push:
    branches:
      - main
    paths:
      - 'packages/*/src/**'
      - 'package.json'
      - 'yarn.lock'
      - '.github/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn install
    - name: Run tests
      run: yarn workspaces foreach run test
    - name: Codecov
      uses: codecov/codecov-action@v1
