name: Codecov
on:
  push:
    branches:
      - main
    paths:
      - 'packages/*/src'
      - 'packages/*/package.json'
      - '.github/**'

jobs:
  codecov:
    name: Execute test suite for drupal-js-sdk
    runs-on: ubuntu-latest
    env:
      node-version: 24.x
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'pnpm'
    - name: Install dependencies
      working-directory: './'
      run: |
        pnpm -r install
        pnpm -r build
        pnpm -r install
    - name: Run test suite
      run: pnpm -r test
    - name: Codecov
      uses: codecov/codecov-action@v2