name: Codecov
on:
  push:
    branches:
      - main
    paths:
      - 'packages/*/src'
      - 'packages/*/package.json'
      - '.github/**'

jobs:
  codecov:
    name: Execute test suite for drupal-js-sdk
    runs-on: ubuntu-latest
    env:
      node-version: 16.x
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      working-directory: './'
      run: |
        pnpm -r install
        pnpm -r build
        pnpm -r install
    # Generate coverage report for @drupal-js-sdk/core 
    - name: Run test suite inside 'packages/core'
      working-directory: './packages/core/'
      run: pnpm test
    - name: Codecov
      uses: codecov/codecov-action@v2
    # Generate coverage report for drupal-js-sdk
    - name: Run test suite inside 'packages/drupal-js-sdk'
      working-directory: './packages/drupal-js-sdk/'
      run: pnpm test
    - name: Codecov
      uses: codecov/codecov-action@v2
