name: Codecov
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run tests
      run: npm run test
    - name: Codecov
      uses: codecov/codecov-action@v1
