name: GitHub pages

on:
  push:
    branches:
      - main
    paths:
      - 'packages/core/src/**'
      - 'packages/core/package.json'
      - '.github/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn install
      - name: Generate typedoc
        run: |
          cd packages/core
          yarn docs
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/core/api
