name: GitHub pages

on:
  push:
    branches:
      - main
    paths:
      - 'packages/*/src/**'
      - 'package.json'
      - 'yarn.lock'
      - '.github/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: |
          yarn install --frozen-lockfile
          npx lerna bootstrap --force-local
          npx lerna run tsc
      - name: Run build
        run: npx lerna run build
      - name: Generate typedoc
        run: npx lerna run docs:typedoc:build
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/core/api
