name: Publish Typedoc to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Generate typedoc
        run: npm run docs:typedoc:build

      - name: Publish to GitHub Pages
        uses: ./
        with:
          dir: api
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}