name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'packages/**/*.md'
      - '.github/**'
      - 'mkdocs.yml'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache 
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
  # gh-pages:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '16'
  #     - run: npm install
  #       working-directory: ./apps/api-reference
  #     - run: npm run docs
  #       working-directory: ./apps/api-reference
  #     - name: Publish to GitHub Pages
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./apps/api-reference/docs
