name: GitHub pages

on:
  push:
    branches:
      - main
    paths:
      - 'packages/core/src/**'
      - 'packages/core/package.json'
      - '.github/**'

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: |
          cd packages/core
          npm install
      - name: Generate typedoc
        run: |
          cd packages/core
          npm run docs
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/core/api
